// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"rezics.com/task-queue/service/auth/ent/key"
	"rezics.com/task-queue/service/auth/ent/user"
)

// KeyCreate is the builder for creating a Key entity.
type KeyCreate struct {
	config
	mutation *KeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBody sets the "body" field.
func (_c *KeyCreate) SetBody(v string) *KeyCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *KeyCreate) SetPermissions(v []string) *KeyCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KeyCreate) SetCreatedAt(v time.Time) *KeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KeyCreate) SetNillableCreatedAt(v *time.Time) *KeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *KeyCreate) SetRevokedAt(v time.Time) *KeyCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *KeyCreate) SetID(v uuid.UUID) *KeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KeyCreate) SetNillableID(v *uuid.UUID) *KeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *KeyCreate) SetUserID(id uuid.UUID) *KeyCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *KeyCreate) SetUser(v *User) *KeyCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the KeyMutation object of the builder.
func (_c *KeyCreate) Mutation() *KeyMutation {
	return _c.mutation
}

// Save creates the Key in the database.
func (_c *KeyCreate) Save(ctx context.Context) (*Key, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KeyCreate) SaveX(ctx context.Context) *Key {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KeyCreate) defaults() {
	if _, ok := _c.mutation.Permissions(); !ok {
		v := key.DefaultPermissions
		_c.mutation.SetPermissions(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := key.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := key.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KeyCreate) check() error {
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Key.body"`)}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "Key.permissions"`)}
	}
	if v, ok := _c.mutation.Permissions(); ok {
		if err := key.PermissionsValidator(v); err != nil {
			return &ValidationError{Name: "permissions", err: fmt.Errorf(`ent: validator failed for field "Key.permissions": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Key.created_at"`)}
	}
	if _, ok := _c.mutation.RevokedAt(); !ok {
		return &ValidationError{Name: "revoked_at", err: errors.New(`ent: missing required field "Key.revoked_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Key.user"`)}
	}
	return nil
}

func (_c *KeyCreate) sqlSave(ctx context.Context) (*Key, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KeyCreate) createSpec() (*Key, *sqlgraph.CreateSpec) {
	var (
		_node = &Key{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(key.Table, sqlgraph.NewFieldSpec(key.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(key.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(key.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(key.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(key.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   key.UserTable,
			Columns: []string{key.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.key_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Key.Create().
//		SetBody(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeyUpsert) {
//			SetBody(v+v).
//		}).
//		Exec(ctx)
func (_c *KeyCreate) OnConflict(opts ...sql.ConflictOption) *KeyUpsertOne {
	_c.conflict = opts
	return &KeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Key.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeyCreate) OnConflictColumns(columns ...string) *KeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeyUpsertOne{
		create: _c,
	}
}

type (
	// KeyUpsertOne is the builder for "upsert"-ing
	//  one Key node.
	KeyUpsertOne struct {
		create *KeyCreate
	}

	// KeyUpsert is the "OnConflict" setter.
	KeyUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Key.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(key.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeyUpsertOne) UpdateNewValues() *KeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(key.FieldID)
		}
		if _, exists := u.create.mutation.Body(); exists {
			s.SetIgnore(key.FieldBody)
		}
		if _, exists := u.create.mutation.Permissions(); exists {
			s.SetIgnore(key.FieldPermissions)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(key.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RevokedAt(); exists {
			s.SetIgnore(key.FieldRevokedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Key.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KeyUpsertOne) Ignore() *KeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeyUpsertOne) DoNothing() *KeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeyCreate.OnConflict
// documentation for more info.
func (u *KeyUpsertOne) Update(set func(*KeyUpsert)) *KeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeyUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *KeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KeyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: KeyUpsertOne.ID is not supported by MySQL driver. Use KeyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KeyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KeyCreateBulk is the builder for creating many Key entities in bulk.
type KeyCreateBulk struct {
	config
	err      error
	builders []*KeyCreate
	conflict []sql.ConflictOption
}

// Save creates the Key entities in the database.
func (_c *KeyCreateBulk) Save(ctx context.Context) ([]*Key, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Key, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KeyCreateBulk) SaveX(ctx context.Context) []*Key {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Key.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeyUpsert) {
//			SetBody(v+v).
//		}).
//		Exec(ctx)
func (_c *KeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *KeyUpsertBulk {
	_c.conflict = opts
	return &KeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Key.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeyCreateBulk) OnConflictColumns(columns ...string) *KeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeyUpsertBulk{
		create: _c,
	}
}

// KeyUpsertBulk is the builder for "upsert"-ing
// a bulk of Key nodes.
type KeyUpsertBulk struct {
	create *KeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Key.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(key.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeyUpsertBulk) UpdateNewValues() *KeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(key.FieldID)
			}
			if _, exists := b.mutation.Body(); exists {
				s.SetIgnore(key.FieldBody)
			}
			if _, exists := b.mutation.Permissions(); exists {
				s.SetIgnore(key.FieldPermissions)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(key.FieldCreatedAt)
			}
			if _, exists := b.mutation.RevokedAt(); exists {
				s.SetIgnore(key.FieldRevokedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Key.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KeyUpsertBulk) Ignore() *KeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeyUpsertBulk) DoNothing() *KeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeyCreateBulk.OnConflict
// documentation for more info.
func (u *KeyUpsertBulk) Update(set func(*KeyUpsert)) *KeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeyUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *KeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
