// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Key is the predicate function for key builders.
type Key func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
