// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"rezics.com/task-queue/service/task/ent/task"
	"rezics.com/task-queue/service/task/ent/worker"
)

// Worker is the model entity for the Worker schema.
type Worker struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// EndOfLife holds the value of the "end_of_life" field.
	EndOfLife time.Time `json:"end_of_life,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkerQuery when eager-loading is set.
	Edges        WorkerEdges `json:"edges"`
	task_worker  *uuid.UUID
	selectValues sql.SelectValues
}

// WorkerEdges holds the relations/edges for other nodes in the graph.
type WorkerEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkerEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Worker) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case worker.FieldEndOfLife:
			values[i] = new(sql.NullTime)
		case worker.FieldID:
			values[i] = new(uuid.UUID)
		case worker.ForeignKeys[0]: // task_worker
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Worker fields.
func (_m *Worker) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case worker.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case worker.FieldEndOfLife:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_of_life", values[i])
			} else if value.Valid {
				_m.EndOfLife = value.Time
			}
		case worker.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_worker", values[i])
			} else if value.Valid {
				_m.task_worker = new(uuid.UUID)
				*_m.task_worker = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Worker.
// This includes values selected through modifiers, order, etc.
func (_m *Worker) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Worker entity.
func (_m *Worker) QueryTask() *TaskQuery {
	return NewWorkerClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Worker.
// Note that you need to call Worker.Unwrap() before calling this method if this Worker
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Worker) Update() *WorkerUpdateOne {
	return NewWorkerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Worker entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Worker) Unwrap() *Worker {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Worker is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Worker) String() string {
	var builder strings.Builder
	builder.WriteString("Worker(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("end_of_life=")
	builder.WriteString(_m.EndOfLife.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Workers is a parsable slice of Worker.
type Workers []*Worker
